### ISSUE TITLE
Fix a/an fails

### ISSUE THREAD

**Issue by simsieg** [feramhq/fix-typos#1]
The module fixes "an using" to "a using" and vice versa.

@@ -891,9 +891,9 @@

895
	- // indent (or not) an using block if no braces are used. Only for C//.Default=True
895
	+ // indent (or not) a using block if no braces are used. Only for C//.Default=True
896
896

**Comment by adius** [comment]
Issue moved to [feramhq/fix-indefinite-article #1](https://github.com/feramhq/fix-indefinite-article/issues/1) via [**ZenHub**](https://www.zenhub.com/)
